name: Release And Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify the Node.js version
      
      - name: Install Dependencies
        run: npm install
        
      - name: Run semantic-release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
  build:
    name: Build
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Set your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build  # Replace with your build command

      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/  # Replace with your build directory
          
  clean-deploy:
    needs: build
    name: Prep Deploy
    runs-on: ubuntu-latest
    steps:       
      - name: 📂 Delete Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: public_html/assets/
          dangerous-clean-slate: true
          
  deploy:
    needs: clean-deploy
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:       
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with: 
          name: build-artifacts

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: public_html/
