name: Semantic Release
on:
  push:
    branches: [ dev ]
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx semantic-release
